In [1]:
import numpy as np

In [15]:
A = np.array([[5,-10,-5],[2,14,2],[-4,-8,6]],dtype = np.float_)
A

array([[  5., -10.,  -5.],
       [  2.,  14.,   2.],
       [ -4.,  -8.,   6.]])

In [16]:
eigen_val, eigen_vec = np.linalg.eig(A)

In [17]:
print(eigen_val)
print(eigen_vec)

[ 5. 10. 10.]
[[-7.45355992e-01 -1.38346519e-15 -6.59218168e-01]
 [ 2.98142397e-01  4.47213595e-01  5.73047151e-01]
 [-5.96284794e-01 -8.94427191e-01 -4.86876134e-01]]


#Eigen Decomposition
A = Q X D X inv(Q) 
Q -> Eigen vectors, D->Diagnol matrix of eigen values

In [18]:
Q = eigen_vec

In [19]:
R = np.linalg.inv(Q)

In [20]:
D = np.diag(eigen_val)

In [21]:
print(Q)

[[-7.45355992e-01 -1.38346519e-15 -6.59218168e-01]
 [ 2.98142397e-01  4.47213595e-01  5.73047151e-01]
 [-5.96284794e-01 -8.94427191e-01 -4.86876134e-01]]


In [22]:
print(R)

[[-1.34164079e+00 -2.68328157e+00 -1.34164079e+00]
 [ 8.94427191e-01  1.37370573e-01 -1.04934870e+00]
 [-9.43124634e-16  3.03389697e+00  1.51694848e+00]]


In [23]:
print(D)

[[ 5.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]


In [24]:
Edecomp = Q.dot(D).dot(R)

In [25]:
Edecomp

array([[  5., -10.,  -5.],
       [  2.,  14.,   2.],
       [ -4.,  -8.,   6.]])

In [26]:
A

array([[  5., -10.,  -5.],
       [  2.,  14.,   2.],
       [ -4.,  -8.,   6.]])