In [15]:
import numpy as np
import numpy.linalg as la

#### Create Link Matrix

In [16]:
L = np.array([[0,1/2,0,0],[1/3,0,0,1/2],[1/3,0,0,1/2],[1/3,1/2,1,0]])
L

array([[0.        , 0.5       , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.5       , 1.        , 0.        ]])

In [8]:
#Lets create initial matrix

In [14]:
r = 100*np.ones(4)/4

In [10]:
#Loop until we get the required tolerance

In [17]:
lastR = r
r = L @ lastR 
i = 0
while la.norm(lastR-r)>0.01:
    lastR = r
    r = L @ lastR
    i=i+1
    print(r)
print(f"{i} number of iterations required for convergenc")

[10.41666667 27.08333333 27.08333333 35.41666667]
[13.54166667 21.18055556 21.18055556 44.09722222]
[10.59027778 26.5625     26.5625     36.28472222]
[13.28125    21.6724537  21.6724537  43.37384259]
[10.83622685 26.11400463 26.11400463 36.93576389]
[13.05700231 22.07995756 22.07995756 42.78308256]
[11.03997878 25.74387539 25.74387539 37.47227045]
[12.87193769 22.41612815 22.41612815 42.29580601]
[11.20806408 25.4385489  25.4385489  37.91483812]
[12.71927445 22.69344042 22.69344042 41.89384471]
[11.34672021 25.1866805  25.1866805  38.27991878]
[12.59334025 22.92219946 22.92219946 41.56226083]
[11.46109973 24.9789105  24.9789105  38.58107927]
[12.48945525 23.11090621 23.11090621 41.28873232]
[11.55545311 24.80751791 24.80751791 38.82951107]
[12.40375896 23.26657324 23.26657324 41.06309457]
[11.63328662 24.6661336  24.6661336  39.03444618]
[12.3330668  23.39498529 23.39498529 40.87696261]
[11.69749265 24.54950357 24.54950357 39.20350021]
[12.27475179 23.50091432 23.50091432 40.72341957]
